version: '2'
services:
  ergodoxcompiler:
    build: .
    volumes:
      - ./qmk_firmware:/data
      - ./adinauer_keymap:/data/keyboards/ergodox/ez/keymaps/adinauer
    command: /bin/bash -c 'cd /data/keyboards/ergodox/ez && make clean && make KEYMAP=adinauer && ls -lah /data/.build/ && cp /data/.build/ergodox_ez_adinauer.hex /data/keyboards/ergodox/ez/keymaps/adinauer/adinauer.hex'
