version: '2'
services:
  ergodoxcompiler:
    build: .
    volumes:
      - ./qmk_firmware:/data
      - ./adinauer_keymap:/data/keyboard/ergodox_ez/keymaps/adinauer
    command: /bin/bash -c 'cd /data/keyboard/ergodox_ez && make clean && make KEYMAP=adinauer && cp /data/keyboard/ergodox_ez/ergodox_ez.hex /data/keyboard/ergodox_ez/keymaps/adinauer/adinauer.hex'
